### ISSUE TITLE
Distorted card images

### ISSUE THREAD

**Issue by designbot** [heisch/gloomhaven-item-db#34]
When viewing item cards as images, the cards are squished vertically to 77% height, while the party management buttons are stretched vertically.

**Comment by heisch** [comment]
@solomojb A small suggestion on how to fix it:

in https://github.com/heisch/gloomhaven-item-db/blob/master/src/components/Tabs/MainView/Items/Grid/itemCard.scss
```scss
.item-card-container-header {
    background: #000;
    border-radius: 15px 15px 0 0;
    display: flex;
    height: 7%;
    justify-content: space-between;
    z-index: 1; // required because of the negative margin-top on .item-card
}
.item-card {
    width: 100%;     
    filter: brightness(105%) contrast(90%);
    height: auto;
    margin-top: -7%; // you can get away with a bit of negative margins since there's no info you lose on the cards
    margin-bottom: -7%;
}
```
